# 05. Read

## 05-01. Read 시작

 Create때 넣어준 데이터를 가져와 읽는 부분을 해볼 것이다.

**해야할 일**

database에 있는 Prodcut 데이터를 가져오는것.

Product를 가져오기 위한 함수를 먼저 생성해야 한다.



먼저 getProducts라는 메서드를 만들 것을 예상하고 testcode를 작성.

```javascript
// test/unit/products.test.js
describe("Product Controller Get", ()=>{
  it("should have a getProducts function", ()=>{
    expect(typeof productController.getProducts).toBe("function")
  })
})
```

```javascript
// controller/products.js
const productModel = require('../models/Products');
...
exports.getProducts = async (req, res, next) =>{
  
}
```



## 05-02. getProducts 단위 테스트 작성(1)

getProducts부분을 완성하기 전에 단위테스를 작성해보자.

`find`라는 메서드를 이용할 것이다.

`it("should call ProductModel.find({})")`

이런 식으로 find에 빈 값을 사용하게 되면, **Product  Collection안의 모든 값을 조건 없이 가져오겠다는 뜻.**

```javascript
// test/unit/products.test.js
describe("Product Controller Get", ()=>{
  ...
  it("should call ProductModel.find({})", async ()=>{
    await productController.getProducts(req, res, next);
    expect(productModel.find).toHaveBeenCalledWith({})
  })
})
```

`toHaveBeenCalledWith()` 어떤 것과 함께 호출되는지 테스트 하는 것.

> ❗ 추천 Extension
>
> Jest Runner를 설치하게되면 각 테스트 상단에 해당 테스트만 Run할 수 있는 Run버튼이 생김



test시 에러나지 않게 controller부분을 작성해보자.

```javascript
// controller/products.js
const Product = require('../models/Products');
const productModel = require('../models/Products');
...
exports.getProducts = async (req, res, next) =>{
  await Product.find({})
}
```

하지만 test해보면 fail이 계속뜰것이다.



**why?**

create의 경우 mock function을 이용해서 계속 create를 관찰하게끔 만들었다.

productModel.find는 그러지 않아서 에러가 발생한 것.

mock함수를 작성해주면 통과하는 것을 볼 수 있다.

```javascript
// test/unit/products.js
const productController = require("../../controller/products");
const productModel = require("../../models/Products");

const httpMocks = require("node-mocks-http");
const newProduct = require("../data/new-product.json");

productModel.create = jest.fn();
productModel.find = jest.fn();
...
describe("Product Controller Get", ()=>{
  it("should have a getProducts function", ()=>{
    expect(typeof productController.getProducts).toBe("function")
  })

  it("should call ProductModel.find({})", async ()=>{
    await productController.getProducts(req, res, next);
    expect(productModel.find).toHaveBeenCalledWith({})
  })
})
```



![find mock함수 결과](./readme_images/05-02. find mock함수 결과.png)





## 05-03. getProducts 단위 테스트 작성(2)

이제 성공했을 때 status를 200으로 보내보자.

먼저 테스트 코드 작성!

```javascript
// test/unit/products.test.js
...
describe("Product Controller Get", ()=>{
  ...
  it("should return 200 response", async () =>{
    await productController.getProducts(req, res, next);
    expect(res.statusCode).toBe(200);
    expect(res._isEndCalled).toBeTruthy();
  })
})
```

```javascript
// controller/products.js
const Product = require('../models/Products');
const productModel = require('../models/Products');
...getProducts = async (req, res, next) =>{
  await Product.find({})
  res.status(200).send();
}
```

※ testcode작성 한 것을 보면, create때 한 것을 반복하는걸 볼 수 있다.



db에서 가져온 데이터를 client에 전달해주자.

여기서 find를 임의로 결과값을 만들어 줘야한다.

(왜냐면 지금은 단위테스트기 때문에 다른 종속성에 영향을 받지 않기 위해서)

```javascript
it("should return json body in response", async () => {
	productModel.find.mockReturnValue()
  })
```

임의의 값은 `new-product.json`처럼 파일을 하나 새로 만들어주자.

```javascript
// test/data/all-product.json
[
  {
    "name": "Gloves",
    "description": "good to wear",
    "price": 15
  },
  {
    "name": "Gloves",
    "description": "good to wear",
    "price": 14
  },
  {
    "name": "Gloves",
    "description": "good to wear",
    "price": 13
  }
]
```



그리고 test파일에서 new-product처럼 all-product를 만들어 넣어주자.

```javascript
const productController = require("../../controller/products");
const productModel = require("../../models/Products");

const httpMocks = require("node-mocks-http");
const newProduct = require("../data/new-product.json");
const allProduct = require("../data/all-product.json");
...

describe("Product Controller Get", ()=>{
  ...
  it("should return json body in response", async () => {
    productModel.find.mockReturnValue(allProduct);
    await productController.getProducts(req, res, next);
    expect(res._getJSONData()).toStrictEqual(allProducts)
  })
})
```

실제 대응하는 코드를 작성해보자.

```javascript
// controller/products.js
const Product = require('../models/Products');
const productModel = require('../models/Products');
...
exports.getProducts = async (req, res, next) =>{
  const allProduts = await Product.find({})
  res.status(200).json(allProduts);
}
```

test하면 통과하는 것을 볼 수 있다.





## 05-04. getProducts 에러 처리 단위 테스트 작성

Product데이터를 가져올 때 에러나면 그에 맞는 에러처리를 해주자.

단위테스트 작성전에 create때 한 것을 다시 보자.

```javascript
it("should handle errors", async ()=>{
    const errorMessage = {message: "description property missing"}; // mongo db에서 전달할 메세지를 임의로 생성
    const rejectedPromise = Promise.reject(errorMessage);
    productModel.create.mockReturnValue(rejectedPromise);
    await productController.createProduct(req, res, next);
    expect(next).toBeCalledWith(errorMessage);
  })
```

어떠한 이유때문에 에러가 날 것이란 것을 message를 지정해놓고,  

`Promise.reject`를 이용해서 에러메세지를 전달.<br/> (mongodb가 비동기로 response를 주기 때문에) 

그럼 controller의 products.js에서 reject가 왔기 때문에 catch에 작성된 next에 error가 전달된다.

그 이유는 reject에 message를 넣어 주었기 떄문. 그래서 toBeCalledWith가 통과하는 것을 알 수 있다.



이제 getProduts에 대해서 작성해보자.

```javascript
// test/unit/products.js
it("should handle errors", async () =>{
    const errorMessage = {message: "Error finding product data"};
    const rejectedPromise = Promise.reject(errorMessage);
    productModel.find.mockReturnValue(rejectedPromise);
    await productController.getProducts(req, res, next);
    expect(next).toHaveBeenCalledWith(errorMessage)
})
```

```javascript
// controller/products.js
const Product = require('../models/Products');
const productModel = require('../models/Products');
...

exports.getProducts = async (req, res, next) =>{
  try{
    const allProduts = await Product.find({})
    res.status(200).json(allProduts);
  }catch(error){
    next(error);
  }
}
```





## 05-05. getProducts 통합 테스트 작성

단위 테스트들이 잘 연동이되서 돌아가는지 통합 테스트를 작성해보자.

```javascript
// test/integration/products.int.test.js
it("GET /api/products", async ()=>{
  const response = await request(app).get("/api/products")
  expect(response.statusCode).toBe(200);
  expect(Array.isArray(response.body)).toBeTruthy();
  expect(response.body[0].name).toBeDefined();
  expect(response.body[0].description).toBeDefined();
})
```

test하면 에러가 날것인데, 그 이유는 route에 설정해주지 않았기 때문.

```javascript
// routes/js
const express = require('express');
const router = express.Router();
const productController = require('./controller/products');

router.post('/', productController.createProduct)
router.get('/', productController.getProducts);
module.exports = router;
```

test시 정상 동작하는 것을 볼 수 있다.





## 05-06. getProductById 단위 테스트 작성(1)

## 05-07. getProductById 단위 테스트 작성(2)

## 05-08. getProductById 통합 테스트 작성(1)

## 05-09. getProductById 통합 테스트 작성(2)

